# Generated by Django 5.0.7 on 2024-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to='resumes'),
        ),
    ]
