# Generated by Django 5.0.7 on 2024-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('certificate_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='certificate')),
            ],
        ),
    ]
