# Generated by Django 5.0.7 on 2024-08-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.course'),
            preserve_default=False,
        ),
    ]
