# Generated by Django 5.0.7 on 2024-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_exam_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='course',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intermediate',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
