# Generated by Django 5.0.7 on 2024-10-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
