# Generated by Django 5.0.7 on 2024-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='correct_ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='optionA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='optionB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='optionC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='optionD',
            field=models.CharField(max_length=100),
        ),
    ]
